backend:
  name: github
  repo: webriq/netlify-cms-blog-starter-template
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: src/markdown/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: publishedDate, label: Published Date, widget: date }
      - { name: excerpt, label: Excerpt, widget: text }
      - { name: body, label: Body, widget: markdown }
      - { name: metaTitle, label: Meta Title }
      - { name: metaKeywords, label: Meta Keywords }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: banner, label: Banner, widget: image }
      - { name: status, label: Status }
      - { name: description, label: Description, widget: text }
      - {
          label: Author,
          name: author,
          widget: relation,
          collection: authors,
          searchFields: [fullName, firstName, lastName],
          valueField: fullName,
        }
      - { name: categories, label: Categories }
      - { name: tags, label: tags }
  - name: authors
    label: Authors
    folder: src/markdown/authors
    create: true
    fields:
      - { label: Layout, name: layout, widget: hidden, default: author }
      - { label: Full Name, name: fullName, widget: string }
      - { label: First Name, name: firstName, widget: string }
      - { label: Last Name, name: lastName, widget: string }
      - { label: Position, name: position, widget: string }
      - { label: Profile Picture, name: profilePicture, widget: image }
      - { label: Email, name: email, widget: string }
